mysql_master:
  image: mysql:5.6.37
  ports:
    - "23306:3306"
  env_file: .env
  environment:
    TZ: Japan
  volumes:
    - ./mounts/mysql_master/mysql.conf.d/:/etc/mysql/mysql.conf.d/
    - ./mounts/mysql_master/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/

mysql_slave:
  image: mysql:5.6.37
  ports:
    - "23316:3306"
  links:
    - mysql_master
  env_file: .env
  volumes:
    - ./mounts/mysql_slave/mysql.conf.d/:/etc/mysql/mysql.conf.d/
    - ./mounts/mysql_slave/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
