nginx:
  image: nginx
  ports:
    - "127.0.0.1:8443:443"
  volumes:
    - ./mounts/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./mounts/nginx/cert.crt:/etc/nginx/cert.crt
    - ./mounts/nginx/cert.key:/etc/nginx/cert.key
    - ./mounts/nginx/srv/:/srv/
