version: '3'
services:
  redis_sh1_master:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command: 
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17010"
    network_mode: host
  redis_sh1_replica:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17011"
    network_mode: host
  redis_sh2_master:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command: 
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17020"
    network_mode: host
  redis_sh2_replica:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17021"
    network_mode: host
  redis_sh3_master:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command: 
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17030"
    network_mode: host
  redis_sh3_replica:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17031"
    network_mode: host
