version: '3'
services:
  redis_sh1_master:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command: 
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17000"
    network_mode: host
  redis_sh1_replica:
    image: redis
    volumes:
      - ./mounts/redis.conf:/etc/redis/redis.conf
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--port 17001"
    network_mode: host
